### ISSUE TITLE
ERROR: Failed to resolve: com.smparkworld.parkimagepicker:parkimagepicker:1.0.0

### ISSUE THREAD

**Issue by UrbanSide** [Park-SM/ParkImagePicker#1]
ERROR: Failed to resolve: com.smparkworld.parkimagepicker:parkimagepicker:1.0.0 

```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        //classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.gms:google-services:4.0.0'

        // Add the Crashlytics Gradle plugin.
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta02'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url "https://jitpack.io"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by Park-SM** [comment]
Thank you very much! :)

**Comment by Park-SM** [comment]
Hi, UrbanSide, 

The reason this is happening is that the README is missing something about the maven repository.

I have little experience with Github, so I just recognized and fixed the problem, but couldn't guide you through it. sorry.

```
maven {
    url 'https://dl.bintray.com/parksm/maven/'
}
```
Adding the maven repository to the build.gradle solves it, but I can't use it now because jcenter is deprecated and gives me a 502 error.

Also, since this library is for personal learning purposes, I do not recommend using it for your app products.

thank you.
